name: 'Action test'
description: 'Action test'
inputs:
  message:
    description: "the message to print"
    required: true
 repo-token:
    description: "a github token for API access"
    required: true
outputs:
  comment-created: # output will be available to future steps 
    description: 'Boolean: comment-created'
branding:
  icon: message-circle
  color: purple
runs:
  using: "node12"
  main: "dist/index.js"
