name: Add PR Comment

# This workflow is triggered on pushes to the repository.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master1
    paths-ignore:
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
          message: |
            This is a multi-line test comment added in PR
            - With GitHub **Markdown**
            - Created by add-pr-comment
