name: 'Check PR title format'
on:
  pull_request:
    branches:
      - master
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
    paths-ignore:
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check PR title format
        uses: ./.github/actions/check-pr-title-format
        id: pr-title-checker
        with:
          # Match pull request titles in the form '[FS-1234]: Message'
          pattern: '^(\[FS-\d+\])((?:\s*,\s*\[FS-\d+\])*)(?:\s*:?\s*([\w\s]+))?'

      - name: Echo previous output
        if: success()
        run: echo '${{ steps.pr-title-checker.outputs.pr-title-format }}'