name: Add PR Comment

on:
  # Trigger the workflow on 'push' event only on the 'master' branch
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Add PR Comment with all ENV variables
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
          message: |
            This is a multi-line test comment added in PR
            - **GITHUB_WORKFLOW** (The name of the workflow.) : ${{ github.workflow }}
            - **GITHUB_ACTION** (The unique identifier of the action) : ${{ github.action }}
            - **GITHUB_ACTOR** : ${{ github.actor }}
            - **GITHUB_REPOSITORY** : ${{ github.repository }}
            - **GITHUB_EVENT_NAME** (The name of the webhook event that triggered the workflow.) : ${{ github.event_name }}
            - **GITHUB_WORKSPACE** (The GitHub workspace directory path. ) : ${{ github.workspace }}
            - **GITHUB_SHA** (The commit SHA that triggered the workflow) : ${{ github.sha }}
            - **GITHUB_REF** (The branch or tag ref that triggered the workflow) : ${{ github.ref }}
