name: frontend_chores

# This workflow is triggered on pushes to the repository.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Run frontend_chores rake task
      run: |
        gem install bundler -v 1.10.6
        bundle install --jobs 4 --retry 3
        bundle exec rake frontend_chores:copy_keys['en']
