name: frontend_chores

# This workflow is triggered on pushes to the repository.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install bundler v 1.10.6
      run: gem install bundler -v 1.10.6
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Run frontend_chores rake task
      run: bundle exec rake frontend_chores:copy_keys['en']
      id: hello
    - name: Echo previous output
      run: echo '${{ steps.hello.outputs }}.'
    - name: Add PR Comment
      uses: mshick/add-pr-comment@v1
      with:
        message: ${{ steps.hello.outputs }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-repeats: false
      
